
# @name CORS preflight request for Maven Search function
OPTIONS http://localhost:3001/maven/search
Origin: http://localhost:3000
Access-Control-Request-Method: GET

> {%
    client.test("Status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("CORS headers", function() {
        client.assert(response.headers.valueOf("Access-Control-Allow-Origin") == "http://localhost:3000", "Access-Control-Allow-Origin incorrect");
        client.assert(response.headers.valueOf("Access-Control-Allow-Methods") == "GET,OPTIONS,POST", "Access-Control-Allow-Methods incorrect");
        client.assert(response.headers.valueOf("Access-Control-Allow-Headers") == "Content-Type", "Access-Control-Allow-Headers incorrect");
        client.assert(response.headers.valueOf("Access-Control-Allow-Credentials") == "true", "Access-Control-Allow-Credentials incorrect");
        client.assert(response.headers.valueOf("Access-Control-Max-Age") == "600", "Access-Control-Max-Age incorrect");
    });
%}

###

# @name Maven Search function
GET http://localhost:3001/maven/search?coordinates=commons-io:commons-io:2.7

> {%
    client.test("Status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("CORS headers", function() {
        client.assert(response.headers.valueOf("Access-Control-Allow-Origin") == "http://localhost:3000", "Access-Control-Allow-Origin incorrect");
    });
    client.test("Body", function() {
        client.assert(response.body.length === 1, "Response contains 1 artifact");
        client.assert(response.body[0].groupId === "commons-io", "groupId is commons-io");
        client.assert(response.body[0].artifactId === "commons-io", "artifactId is commons-io");
        client.assert(response.body[0].version === "2.7", "version is 2.7");
    });
%}

###

# @name CORS preflight request for JAPICC Check function
OPTIONS http://localhost:3001/japicc/check
Origin: http://localhost:3000
Access-Control-Request-Method: POST
Access-Control-Allow-Headers: content-type

> {%
    client.test("Status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("CORS headers", function() {
        client.assert(response.headers.valueOf("Access-Control-Allow-Origin") == "http://localhost:3000", "Access-Control-Allow-Origin incorrect");
        client.assert(response.headers.valueOf("Access-Control-Allow-Methods") == "GET,OPTIONS,POST", "Access-Control-Allow-Methods incorrect");
        client.assert(response.headers.valueOf("Access-Control-Allow-Headers") == "Content-Type", "Access-Control-Allow-Headers incorrect");
        client.assert(response.headers.valueOf("Access-Control-Allow-Credentials") == "true", "Access-Control-Allow-Credentials incorrect");
        client.assert(response.headers.valueOf("Access-Control-Max-Age") == "600", "Access-Control-Max-Age incorrect");
    });
%}

###

# @name JAPICC Check function
POST http://localhost:3001/japicc/check
Content-Type: application/json

{
  "oldVersion": "commons-io:commons-io:2.7",
  "newVersion": "commons-io:commons-io:2.11.0"
}

> {%
    client.test("Status code", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("CORS headers", function() {
        client.assert(response.headers.valueOf("Access-Control-Allow-Origin") == "http://localhost:3000", "Access-Control-Allow-Origin incorrect");
    });
    client.test("Body", function() {
        client.assert(response.body.reportURL === "http://online.jarhc.org/reports/report-89136839f409d413748241df527e6e5afaa826d520d434493f37c9d17673c5d8.html", "reportURL contains report URL");
        client.assert(response.body.errorMessage === "", "errorMessage is empty");
    });
%}
