
# @name Hello World test function
GET https://enw25uywda.execute-api.eu-central-1.amazonaws.com/Prod/hello

###

# @name JAPICC check function
POST https://api.jarhc.org/japicc/check
Content-Type: application/json

{
  "oldVersion": "commons-io:commons-io:2.7",
  "newVersion": "commons-io:commons-io:2.11.0"
}