
# @name Maven Search function
GET https://api.jarhc.org/maven/search?coordinates=commons-io:commons-io:2.7

###

# @name Maven Search function (not found)
GET https://api.jarhc.org/maven/search?coordinates=unknown:unknown:0.0.1

###

# @name Maven Search function (invalid coordinates)
GET https://api.jarhc.org/maven/search?coordinates=unknown

###

# @name Maven Search function (missing parameter)
GET https://api.jarhc.org/maven/search

###

# @name JAPICC Check function
POST https://api.jarhc.org/japicc/check
Content-Type: application/json

{
  "oldVersion": "commons-io:commons-io:2.7",
  "newVersion": "commons-io:commons-io:2.11.0"
}

###

# @name JAPICC Check function (not found)
POST https://api.jarhc.org/japicc/check
Content-Type: application/json

{
  "oldVersion": "unknown:unknown:0.0.1",
  "newVersion": "unknown:unknown:0.0.2"
}

### CORS ---------------------------------------

# @name CORS preflight request for Maven Search function
OPTIONS https://api.jarhc.org/maven/search
Origin: http://online.jarhc.org
Access-Control-Request-Method: GET

###

# @name CORS preflight request for JAPICC Check function
OPTIONS https://api.jarhc.org/japicc/check
Origin: http://online.jarhc.org
Access-Control-Request-Method: POST
Access-Control-Allow-Headers: content-type
