version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jarhc-online-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lcbyi0cw90q3"
s3_prefix = "jarhc-online-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["JapiccCheckFunction=837783538267.dkr.ecr.eu-central-1.amazonaws.com/jarhconlineappc576971f/japicccheckfunctionf49d3734repo"]
