AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "jarhc-online-app - JAR Health Check Online serverless application."

Parameters:

  ApiDomain:
    Description: Domain name for API gateway
    Type: String
    Default: api.jarhc.org

  CognitoUserPoolARN:
    Description: Cognito User Pool ARN
    Type: String
    Default: arn:aws:cognito-idp:eu-central-1:837783538267:userpool/eu-central-1_duUV8DgO7

  WebsiteDomain:
    Description: Domain name for public website (CloudFront distribution)
    Type: String
    Default: online.jarhc.org

  WebsiteURL:
    Description: URL for public website (CloudFront distribution)
    Type: String
    Default: https://online.jarhc.org

  WebsiteCertificateARN:
    Description: ARN of SSL certificate in us-east-1 required for CloudFront
    Type: String
    # see region "us-east-1", CloudFormation stack "jarhc-online-cert", output "WebsiteCertificateARN"
    Default: arn:aws:acm:us-east-1:837783538267:certificate/3fa0002b-0667-4e67-b8c5-d228a4341811

  BucketName:
    Description: Name of S3 bucket hosting public website
    Type: String
    Default: online.jarhc.org

  BucketURL:
    Description: URL of S3 bucket hosting JARHC reports
    Type: String
    Default: https://online.jarhc.org

  LogsBucket:
    Description: Full name of S3 bucket for logs
    Type: String
    Default: aws-cloud-reports.s3.amazonaws.com

  DnsZoneID:
    Description: ID of hosted DNS zone
    Type: String
    Default: Z39VOOPW73P7H0

Globals:

  Function:
    Timeout: 5

  Api:
    Auth:
      ApiKeyRequired: false
      DefaultAuthorizer: CognitoAuthorizer
      AddDefaultAuthorizerToCorsPreflight: false
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !Ref CognitoUserPoolARN
          Identity:
            Header: Authorization # default
            ReauthorizeEvery: 300 # 300 seconds = 5 minutes (default)
    Cors:
      AllowOrigin: !Sub "'${WebsiteURL}'"
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type,Authorization'"
      AllowCredentials: true
      MaxAge: "'600'" # cache results of a preflight request for 10 minutes
    GatewayResponses:
      DEFAULT_4XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: !Sub "'${WebsiteURL}'"
            Access-Control-Allow-Credentials: "'true'"
      DEFAULT_5XX:
        ResponseParameters:
          Headers:
            Access-Control-Allow-Origin: !Sub "'${WebsiteURL}'"
            Access-Control-Allow-Credentials: "'true'"
    EndpointConfiguration:
      Type: REGIONAL
    Domain:
      # Domain name and SSL certificate for API gateway
      DomainName: !Ref ApiDomain
      CertificateArn: !Ref ApiCertificate
      EndpointConfiguration: REGIONAL # default
      Route53:
        # see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-route53configuration.html
        HostedZoneId: !Ref DnsZoneID
        EvaluateTargetHealth: false
        IpV6: false
    MethodSettings:
      - HttpMethod: "*"
        ResourcePath: "/*"
        ThrottlingRateLimit: 10
        ThrottlingBurstLimit: 20

Resources:

  ResourceGroup:
    Type: "AWS::ResourceGroups::Group"
    Properties:
      Name: "jarhc-online-resource-group"
      Description: "Resource group for jarhc-online-app"

  JapiccJobQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: japicc-job-queue
      VisibilityTimeout: 60 # must be >= Lambda function timeout

  JapiccJobQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref JapiccJobQueue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: RestApiFunctionRole # grant access to rest-api function
            Resource: !GetAtt JapiccJobQueue.Arn
            Effect: Allow
            Action:
              - 'sqs:GetQueueUrl'
              - 'sqs:SendMessage'
            Principal:
              AWS: !GetAtt RestApiFunctionRole.Arn

  # Lambda function
  RestApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: rest-api
      CodeUri: ./rest-api
      Handler: rest-api
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        AuthValidate:
          Type: Api
          Properties:
            Path: /auth/validate
            Method: GET
        JapiccSubmit:
          Type: Api
          Properties:
            Path: /japicc/submit
            Method: POST
        MavenSearch:
          Type: Api
          Properties:
            Path: /maven/search
            Method: GET
            Auth:
              Authorizer: NONE
      Environment:
        Variables:
          WEBSITE_URL: !Ref WebsiteURL
          BUCKET_NAME: !Ref BucketName
          BUCKET_URL: !Ref BucketURL

  # Lambda function
  JapiccCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: japicc-check
      PackageType: Image
      Architectures:
        - x86_64
      # max price per execution:
      # MemorySize * Timeout / 1024 * $0.0000166667 = $0.001000002
      MemorySize: 1024 # increase memory size to 1 GB for JAPICC
      Timeout: 60 # increase timeout to 60 seconds for JAPICC
      Events:
        CatchAll:
          Type: SQS
          Properties:
            Queue: !GetAtt JapiccJobQueue.Arn
            BatchSize: 1
      Environment:
        Variables:
          BUCKET_NAME: !Ref BucketName
          BUCKET_URL: !Ref BucketURL
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./japicc-check
      Dockerfile: Dockerfile

  # SSL certificate for API gateway
  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref ApiDomain
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref ApiDomain
          HostedZoneId: !Ref DnsZoneID

  # S3 Bucket for public website
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      CorsConfiguration:
        CorsRules:
          - Id: CorsRule1
            AllowedOrigins:
              - "*"
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - "*"
            MaxAge: 600
      LifecycleConfiguration:
        Rules:
          - Id: AutoCleanup
            Status: Enabled
            Prefix: "reports/"
            ExpirationInDays: 30

  # S3 Bucket Policy for public website
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ReadAccessForEveryone # grant read access to everyone
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
            Effect: Allow
            Action:
              - 's3:GetObject'
            Principal: '*'
          - Sid: ReadWriteAccessForJapiccCheckFunctionRole # grant read and write access to JapiccCheck function
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Principal:
              AWS: !GetAtt JapiccCheckFunctionRole.Arn

  # CloudFront Distribution for public website
  WebsiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref WebsiteDomain
        HttpVersion: http2
        Origins:
          - Id: DefaultOrigin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref WebsiteCertificateARN
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
          Compress: true
          TargetOriginId: DefaultOrigin
          ViewerProtocolPolicy: redirect-to-https
        Logging:
          Bucket: !Ref LogsBucket
          Prefix: "cloudfront-access-logs/"
          IncludeCookies: false

  # Route 53 DNS record for public website (CloudFront distribution)
  WebsiteDnsRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref DnsZoneID
      RecordSets:
        - Name: !Ref WebsiteDomain
          Type: A
          AliasTarget:
            DNSName: !GetAtt WebsiteCloudFrontDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
            EvaluateTargetHealth: false

Outputs:

  ApiGatewayUrl:
    Description: "Base URL of API Gateway."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  WebsiteBucketUrl:
    Description: "Public URL of S3 Bucket."
    Value: !Sub "https://${WebsiteBucket.RegionalDomainName}/"

  WebsiteCloudFrontDistributionUrl:
    Description: "Public URL of CloudFront Distribution."
    Value: !Sub "https://${WebsiteCloudFrontDistribution.DomainName}/"
