AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "jarhc-online-app - JAR Health Check Online serverless application."

Parameters:
  ApiDomain:
    Type: String
    Default: api.jarhc.org
  WebsiteDomain:
    Type: String
    Default: online.jarhc.org
  WebsiteURL:
    Type: String
    Default: https://online.jarhc.org
  WebsiteCertificateARN:
    # ARN of SSL certificate in us-east-1 required for CloutFront
    Type: String
    Default: arn:aws:acm:us-east-1:837783538267:certificate/b18b61c2-4f55-4f98-8563-a7b6fc5af699
  BucketName:
    Type: String
    Default: online.jarhc.org
  BucketURL:
    Type: String
    Default: https://online.jarhc.org
  DnsZoneID:
    Type: String
    Default: Z39VOOPW73P7H0

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

  Api:
    Cors:
      AllowOrigin: !Sub "'${WebsiteURL}'"
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowCredentials: true
      MaxAge: "'600'" # cache results of a preflight request for 10 minutes
    EndpointConfiguration:
      Type: REGIONAL
    Domain:
      DomainName: !Ref ApiDomain
      CertificateArn: !Ref ApiCertificate
      EndpointConfiguration: REGIONAL # default
      Route53:
        # see https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-route53configuration.html
        HostedZoneId: !Ref DnsZoneID
        EvaluateTargetHealth: false
        IpV6: false

Resources:

  ResourceGroup:
    Type: "AWS::ResourceGroups::Group"
    Properties:
      Name: "jarhc-online-resource-group"
      Description: "Resource group for jarhc-online-app"

  JapiccCheckFunction:
    Type: AWS::Serverless::Function # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      # max price per execution:
      # MemorySize * Timeout / 1024 * $0.0000166667 = $0.001000002
      MemorySize: 1024 # increase memory size to 1 GB for JAPICC
      Timeout: 60 # increase timeout to 60 seconds for JAPICC
      Events:
        CatchAll:
          Type: Api # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /japicc/check
            Method: POST
      Environment:
        Variables:
          WEBSITE_URL: !Ref WebsiteURL
          BUCKET_NAME: !Ref BucketName
          BUCKET_URL: !Ref BucketURL
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./japicc-check
      Dockerfile: Dockerfile

  MavenSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./maven-search
      Handler: maven-search
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /maven/search
            Method: GET
      Environment:
        Variables:
          WEBSITE_URL: !Ref WebsiteURL

  # SSL certificate for public website (must be in us-east-1 !!!)
  # WebsiteCertificate:
  #  Type: AWS::CertificateManager::Certificate
  #  Properties:
  #    DomainName: !Ref WebsiteDomain
  #    ValidationMethod: DNS
  #    DomainValidationOptions:
  #      - DomainName: !Ref WebsiteDomain
  #        HostedZoneId: !Ref DnsZoneID

  # SSL certificate for API gateway
  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref ApiDomain
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref ApiDomain
          HostedZoneId: !Ref DnsZoneID

  # S3 Bucket for public website
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      LifecycleConfiguration:
        # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig.html
        Rules:
          - Id: AutoCleanup
            Status: Enabled
            Prefix: "reports/"
            ExpirationInDays: 7
      # CorsConfiguration: https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html

  # S3 Bucket Policy for public website
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ReadAccessForEveryone # grant read access to everyone
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
            Effect: Allow
            Action:
              - 's3:GetObject'
            Principal: '*'
          - Sid: ReadWriteAccessForJapiccCheckFunctionRole # grant read and write access to JapiccCheck function
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Principal:
              AWS: !GetAtt JapiccCheckFunctionRole.Arn

  # CloudFront Distribution for public website
  WebsiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref WebsiteDomain
        HttpVersion: http2
        Origins:
          - Id: DefaultOrigin
            DomainName: !Sub "${WebsiteBucket.RegionalDomainName}"
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref WebsiteCertificateARN
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          # CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # CachingOptimized
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # CachingDisabled
          Compress: true
          TargetOriginId: DefaultOrigin
          ViewerProtocolPolicy: redirect-to-https

  WebsiteDnsRecord:
    # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-route53.html#w2ab1c23c21c80c11
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref DnsZoneID
      RecordSets:
        - Name: !Ref WebsiteDomain
          Type: A
          AliasTarget:
            DNSName: !Sub "${WebsiteCloudFrontDistribution.DomainName}"
            HostedZoneId: Z2FDTNDATAQYW2
            EvaluateTargetHealth: false

Outputs:
  ApiGatewayUrl:
    Description: "Base URL of API Gateway."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  WebsiteBucketUrl:
    Description: "Public URL of S3 Bucket."
    Value: !Sub "https://${WebsiteBucket.RegionalDomainName}/"
  WebsiteCloudFrontDistributionUrl:
    Description: "Public URL of CloudFront Distribution."
    Value: !Sub "https://${WebsiteCloudFrontDistribution.DomainName}/"
