AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "jarhc-online-app - JAR Health Check Online serverless application."

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:

  ResourceGroup:
    Type: "AWS::ResourceGroups::Group"
    Properties:
      Name: "jarhc-online-resource-group"
      Description: "Resource group for jarhc-online-app"

  JapiccCheckFunction:
    Type: AWS::Serverless::Function # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      # max price per execution:
      # MemorySize * Timeout / 1024 * $0.0000166667 = $0.001000002
      MemorySize: 1024 # increase memory size to 1 GB for JAPICC
      Timeout: 60 # increase timeout to 60 seconds for JAPICC
      Events:
        CatchAll:
          Type: Api # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /japicc/check
            Method: POST
      Environment: # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE # TODO: pass bucket region and name to function
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./japicc-check
      Dockerfile: Dockerfile

  # SSL certificate for public site online.jarhc.org
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: online.jarhc.org
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: online.jarhc.org
          HostedZoneId: Z39VOOPW73P7H0

  # S3 Bucket for public site online.jarhc.org
  JarhcOnlineBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: online.jarhc.org
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
      LifecycleConfiguration:
        # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig.html
        Rules:
          - Id: AutoCleanup
            Status: Enabled
            Prefix: "reports/"
            ExpirationInDays: 7
      # CorsConfiguration: https://docs.aws.amazon.com/AmazonS3/latest/userguide/cors.html

  # S3 Bucket Policy for public site online.jarhc.org
  JarhcOnlineBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref JarhcOnlineBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ReadAccessForEveryone # grant read access to everyone
            Resource: !Sub "arn:aws:s3:::${JarhcOnlineBucket}/*"
            Effect: Allow
            Action:
              - 's3:GetObject'
            Principal: '*'
          - Sid: ReadWriteAccessForJapiccCheckFunctionRole # grant read and write access to JapiccCheck function
            Resource: !Sub "arn:aws:s3:::${JarhcOnlineBucket}/*"
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:PutObject'
            Principal:
              AWS: !GetAtt JapiccCheckFunctionRole.Arn

  JarhcOnlineDnsRecord:
    # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-recordset.html
    Type: AWS::Route53::RecordSet
    Properties:
      Name: online.jarhc.org
      HostedZoneId: Z39VOOPW73P7H0
      Type: A
      AliasTarget:
        # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget-1.html
        # see https://docs.aws.amazon.com/general/latest/gr/s3.html#s3_website_region_endpoints
        DNSName: s3-website.eu-central-1.amazonaws.com # S3 website endpoint where bucket "online.jarhc.org" has been created
        HostedZoneId: Z21DNDUVLTQW6Q # Route 53 Hosted Zone ID for S3 website endpoint where bucket "online.jarhc.org" has been created
        EvaluateTargetHealth: false

Outputs:
  ApiGatewayUrl:
    Description: "Base URL of API Gateway."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  JarhcOnlineBucketUrl:
    Description: "Public URL of S3 Bucket for online.jarhc.org."
    Value: !Sub "https://${JarhcOnlineBucket.RegionalDomainName}/"
