AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "jarhc-online-app - JAR Health Check Online serverless application."

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:

  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: GET
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./hello-world
      Dockerfile: Dockerfile

  JapiccCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      # max price per execution:
      # MemorySize * Timeout / 1024 * $0.0000166667 = $0.001000002
      MemorySize: 1024 # increase memory size to 1 GB for JAPICC
      Timeout: 60 # increase timeout to 60 seconds for JAPICC
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /japicc/check
            Method: POST
      Environment:
        Variables:
          PARAM1: VALUE
    Metadata:
      DockerTag: go1.x-v1
      DockerContext: ./japicc-check
      Dockerfile: Dockerfile

Outputs:
  JapiccCheckApi:
    Description: "API Gateway endpoint base URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
