# @name Get root
GET http://localhost:8080

###

# @name Get JAPICC version
GET http://localhost:8080/japicc/version

###

# @name Search Maven artifact
GET http://localhost:8080/maven/search?coordinates=commons-io:commons-io:2.7

###

# @name Search Maven artifact (not found)
GET http://localhost:8080/maven/search?coordinates=unknown:unknown:0.0.1

###

# @name Search Maven artifact (invalid coordinates)
GET http://localhost:8080/maven/search?coordinates=unknown

###

# @name Search Maven artifact (missing parameter)
GET http://localhost:8080/maven/search

####

# @name Run JAPICC check
POST http://localhost:8080/japicc/check
Content-Type: application/json

{
  "oldVersion": "commons-io:commons-io:2.7",
  "newVersion": "commons-io:commons-io:2.11.0"
}

###

# @name Download report
GET http://localhost:8080/japicc/report/report-89136839f409d413748241df527e6e5afaa826d520d434493f37c9d17673c5d8.html
