version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jarhc-online-cert"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-h4lq8dxbf3zl"
s3_prefix = "jarhc-online-cert"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
