AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SSL certificate for public website (must be in us-east-1 !!!)

Parameters:

  WebsiteDomain:
    Description: Domain name for public website (CloudFront distribution)
    Type: String
    Default: online.jarhc.org

  DnsZoneID:
    Description: ID of hosted DNS zone
    Type: String
    Default: Z39VOOPW73P7H0

Resources:

  WebsiteCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref WebsiteDomain
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref WebsiteDomain
          HostedZoneId: !Ref DnsZoneID

Outputs:

  WebsiteCertificateArn:
    Description: "Website Certificate ARN"
    Value: !Ref WebsiteCertificate
