version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jarhc-online-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lcbyi0cw90q3"
s3_prefix = "jarhc-online-api"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = ["JapiccCheckFunction=837783538267.dkr.ecr.eu-central-1.amazonaws.com/jarhc-online-api"]
