version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "jarhc-online-website"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-lcbyi0cw90q3"
s3_prefix = "jarhc-online-website"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
image_repositories = []
