AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Public website

Parameters:

  WebsiteDomain:
    Description: Domain name for public website (CloudFront distribution)
    Type: String
    Default: online.jarhc.org

  WebsiteCertificateARN:
    Description: ARN of SSL certificate in us-east-1 required for CloudFront
    Type: String
    # see region "us-east-1", CloudFormation stack "jarhc-online-cert", output "WebsiteCertificateARN"
    Default: arn:aws:acm:us-east-1:837783538267:certificate/3fa0002b-0667-4e67-b8c5-d228a4341811

  WebsiteLogsBucket:
    Description: Full name of S3 bucket for logs
    Type: String
    Default: aws-cloud-reports.s3.amazonaws.com

  DnsZoneID:
    Description: ID of hosted DNS zone
    Type: String
    Default: Z39VOOPW73P7H0

Globals:

  Function:
    Timeout: 5

Resources:

  # S3 Bucket for public website
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref WebsiteDomain
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: AutoCleanup
            Status: Enabled
            Prefix: "reports/"
            ExpirationInDays: 30

  # S3 Bucket Policy for public website
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: "cloudfront.amazonaws.com"
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
            Resource:
              - !Sub "arn:aws:s3:::${WebsiteBucket}"
              - !Sub "arn:aws:s3:::${WebsiteBucket}/*"
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudfront::${AWS::AccountId}:distribution/${WebsiteCloudFrontDistribution.Id}"

  WebsiteOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: WebsiteOriginAccessControl
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # CloudFront Distribution for public website
  WebsiteCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Aliases:
          - !Ref WebsiteDomain
        HttpVersion: http2
        Origins:
          - Id: DefaultOrigin
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            OriginAccessControlId: !GetAtt WebsiteOriginAccessControl.Id
            S3OriginConfig:
              OriginAccessIdentity: ""
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref WebsiteCertificateARN
          MinimumProtocolVersion: TLSv1.2_2021
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad # Managed: CachingDisabled
          ResponseHeadersPolicyId: 67f7725c-6f97-4210-82d7-5512b31e9d03 # Managed: SecurityHeadersPolicy
          Compress: true
          TargetOriginId: DefaultOrigin
          ViewerProtocolPolicy: redirect-to-https
        Logging:
          Bucket: !Ref WebsiteLogsBucket
          Prefix: "cloudfront-access-logs/"
          IncludeCookies: false

  # Route 53 DNS record for public website (CloudFront distribution)
  WebsiteDnsRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref DnsZoneID
      RecordSets:
        - Name: !Ref WebsiteDomain
          Type: A
          AliasTarget:
            DNSName: !GetAtt WebsiteCloudFrontDistribution.DomainName
            HostedZoneId: Z2FDTNDATAQYW2
            EvaluateTargetHealth: false

Outputs:

  WebsiteCloudFrontDistributionUrl:
    Description: "Public URL of CloudFront Distribution."
    Value: !Sub "https://${WebsiteCloudFrontDistribution.DomainName}/"
