name: Build react-app

on:
  push:
    paths:
      - 'react-app/**'
      - '.github/workflows/build-react-app.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PUSH_GRADLE_OPTIONS: ''

    steps:

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci
      working-directory: react-app

    - name: Build with NPM
      run: npm run build
      working-directory: react-app

    - name: Upload dist
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: react-app/dist
