name: Build react-app

on:
  push:
    paths:
      - 'react-app/**'
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PUSH_GRADLE_OPTIONS: ''

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
      with:
        working-directory: react-app

    - name: Build with NPM
      run: npm run build
      with:
        working-directory: react-app
