name: Build react-app

on:
  push:
    paths:
      - 'react-app/**'
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      PUSH_GRADLE_OPTIONS: ''

    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm ci
      working-directory: react-app

    - name: Build with NPM
      run: npm run build
      working-directory: react-app

    - name: Upload build
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: react-app/build
        retention-days: 7
